# Given two strings s and t which consist of only
# lowercase letters.
#
# String t is generated by random shuffling string
# s and then add one more letter at a random position.
#
# Find the letter that was added in t.

def find_the_difference(s, t)
  s_hash = Hash.new(0)
  t_hash = Hash.new(0)
  first = s.split("")
  last = t.split("")
  first.map { |letter| s_hash[letter] += 1 }
  last.map { |letter| t_hash[letter] += 1 }
  (t_hash.to_a - s_hash.to_a).flatten[0]
end